### ISSUE TITLE
submodule fetch fails

### ISSUE THREAD

**Issue by cgwalters** [cgwalters/mantle#1]
On the `rhcos` branch:

```
$ git submodule update --init
error: Server does not allow request for unadvertised object 2e2164d47aea325d9a9eeae11053313ece332f41
Fetched in submodule path 'mantle', but it did not contain 2e2164d47aea325d9a9eeae11053313ece332f41. Direct fetching of that commit failed.
$ cat .git/config
...
[submodule "mantle"]
        active = true
        url = https://github.com/cgwalters/mantle
```

Originally I had that commit pointed at to by the [8gb-orig branch](https://github.com/cgwalters/mantle/tree/8gb-orig) but that appeared not to work, so I just pushed it to [master](https://github.com/cgwalters/mantle/tree/master) but that still doesn't work...

**Comment by cgwalters** [comment]
I found this [StackOverflow thread](https://superuser.com/questions/1240216/what-does-the-git-error-message-server-does-not-allow-request-for-unadvertised) which makes sense...but I do have refs pointing to the commit.

**Comment by cgwalters** [comment]
Of course since I took the time to write this up I figured it out; one needs to `git submodule sync` after switching branches which change a submodule's URL.

**Comment by jlebon** [comment]
I found https://github.com/AppImage/AppImageKit/issues/511, which mentions trying out `git submodule sync` or using `git submodule update --depth BIG_NUMBER`.

**Comment by jlebon** [comment]
Damn, 5 seconds.

**Comment by avtrujillo** [comment]
What worked for me was looking at the [commit history for /vendor](https://github.com/leksah/leksah/commits/master/vendor) and moving the head in my cloned repository to the last commit that passed all checks, which is currently 6a7b915d68976dd2db2417f3933f2fdafceeba3e. I then checkout out a new branch, and ran `git submodule update --init --recursive` and everything worked fine

...with the exception of the fact that I ran out of room on my liinux partition while running `./leksah-nix.sh`, but that's unlikely to be a problem for you
